### ISSUE TITLE
Styling for react-template

### ISSUE THREAD

**Issue by chrishelgert** [danielbayerlein/honeycomb#38]
the honeycomb-generator needs some styling for its react-components
- postcss / scss / aphrodite / radium
- autoprefixer
- extend unit-tests for new generator-cases

**Comment by chrishelgert** [comment]
first favorite was [styled-components](https://github.com/styled-components/styled-components) but there is a [bug](https://github.com/styled-components/styled-components/issues/157) with webpack and babel - so we would have to duplicate our babel-config.

i will choose aphrodite or radium in the first step

**Comment by danielbayerlein** [comment]
@chrishelgert Please see https://github.com/styled-components/styled-components/issues/157#issuecomment-257603430

**Comment by chrishelgert** [comment]
@danielbayerlein  yeah i know:
```javascript
module: {
    rules: [
      {
        test: /\.js$/,
        loader: 'babel',
        query: {
          presets: ['react', ['es2015', { modules: false }]],
          plugins: ['react-hot-loader/babel', 'transform-runtime', 'transform-class-properties', 'transform-object-rest-spread'],
        },
        exclude: /node_modules/,
      },
    ],
  }
```

so it will run, but we have to duplicate our babel-config + removing eslint from this rule. i will look further at it

**Comment by chrishelgert** [comment]
```javascript
// layout/default.js

```
