### ISSUE TITLE
Layout Service

### ISSUE THREAD

**Issue by chrishelgert** [danielbayerlein/honeycomb#50]
Create the honeycomb-layout for [tailor](https://github.com/zalando/tailor)

**Comment by danielbayerlein** [comment]
I've published my middleware, see https://github.com/danielbayerlein/honeycomb/tree/layout-service

**Comment by chrishelgert** [comment]
TODO´s:
* change template to use absolute-link for js/css-files or other solution - currently 404
* maybe extract middleware into extra package
* demo-setup (with reverse-proxy and co?)
* unit-tests

i´m working on it :)

**Comment by danielbayerlein** [comment]
See #59
