### ISSUE TITLE
Handle global libraries

### ISSUE THREAD

**Issue by chrishelgert** [danielbayerlein/honeycomb#69]
We need a solution for handle libraries, that are used by more than 1 honeycomb-template.

example:
* react, react-dom will be served with honeycomb-asset
* react, react-dom are externals in honeycomb-template (webpack.config, maybe only in production)

maybe we find a better/cleaner solution

**Comment by chrishelgert** [comment]
@danielbayerlein should i use styling to the asset-service?
or leave it for the future ? (when we know which styling-framework we use (bootstrap, ...))

**Comment by danielbayerlein** [comment]
@chrishelgert At the moment, I would not include a styling framework e.g. Bootstrap...

**Comment by danielbayerlein** [comment]
PR: #80
