### ISSUE TITLE
honeycomb-server

### ISSUE THREAD

**Issue by danielbayerlein** [danielbayerlein/honeycomb#75]
I think it makes sense to create a `honeycomb-server` package with `hapi.js`.

**Comment by danielbayerlein** [comment]
@chrishelgert What do you think about that?

**Comment by chrishelgert** [comment]
What do you mesn with this?
What will be part of honeycomb-server?

**Comment by danielbayerlein** [comment]
`honecomb-server` is a dependency of every `honeycomb-service`. It includes `hapi.js` and the configuration for e.g. `gzip` or `http2`. For example https://github.com/electrode-io/electrode-server. So we have only one package with the `hapi.js` dependency.

I'm not sure it makes sense at the moment. Let's talk about it on Monday.

**Comment by danielbayerlein** [comment]
PR: #82
