### ISSUE TITLE
Naming convention for test files

### ISSUE THREAD

**Issue by danielbayerlein** [danielbayerlein/honeycomb#86]
Our test files do not have a uniform name:

* `eslint-config-honeycomb` -> `*-test.js`
* `generator-honeycomb` -> `*-test.js`
* `honeycomb-assets` -> `*.test.js`
* `honeycomb-health-middleware` -> `*.js`
* `honeycomb-info-middleware` -> `*.js`
* `honeycomb-layout` -> `*-test.js`
* `honeycomb-logging-middleware` -> `*.js`
* `honeycomb-registry-client`-> `*-test.js`
* `honeycomb-server` -> `*.js`

@chrishelgert Do you prefer `*-test.js` or `*.test.js`?

**Comment by chrishelgert** [comment]
I would prefer the .test.js syntax 👌
